In [1]:
# chain rule: - dz/dy = dz/dx * dx/dy
# to calculate the final loss we need the local gradients

In [2]:
# 3 steps :-
# forward pass : compute loss
# compute local gradients 
# backward pass : compute dLoss/dWeights using chain rule

In [1]:
import torch

In [2]:
#FORWARD PASS

x = torch.tensor(1.0)
print(x)
# actual output
y = torch.tensor(1.0)
print(y)
# random weight
weight = torch.rand(1 , requires_grad = True)
print(weight)
# calculating the predicted output
y_hat = x*weight
print(y_hat)
#calculating the loss
loss = (y_hat - y)**2
print(loss)

tensor(1.)
tensor(1.)
tensor([0.8574], requires_grad=True)
tensor([0.8574], grad_fn=<MulBackward0>)
tensor([0.0203], grad_fn=<PowBackward0>)


In [5]:
# BACKWARD PASS
loss.backward()

print(weight.grad)

# update the weights
# run the forward and backward pass multiple times

tensor([-0.8866])
